# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: raft.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'raft.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nraft.proto\x12\x04raft\"\x07\n\x05\x45mpty\"8\n\x12RequestVoteRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0c\x63\x61ndidate_id\x18\x02 \x01(\x05\"9\n\x13RequestVoteResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x14\n\x0cvote_granted\x18\x02 \x01(\x08\"7\n\x14\x41ppendEntriesRequest\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x11\n\tleader_id\x18\x02 \x01(\x05\"6\n\x15\x41ppendEntriesResponse\x12\x0c\n\x04term\x18\x01 \x01(\x05\x12\x0f\n\x07success\x18\x02 \x01(\x08\"\x0f\n\rStatusRequest\"I\n\x0bStatusReply\x12\x0f\n\x07node_id\x18\x01 \x01(\x05\x12\x0c\n\x04role\x18\x02 \x01(\t\x12\x0c\n\x04term\x18\x03 \x01(\x05\x12\r\n\x05\x61live\x18\x04 \x01(\x08\"\r\n\x0bPingRequest\"\x1c\n\tPingReply\x12\x0f\n\x07message\x18\x01 \x01(\t2\xa2\x02\n\x0bRaftService\x12\x42\n\x0bRequestVote\x12\x18.raft.RequestVoteRequest\x1a\x19.raft.RequestVoteResponse\x12H\n\rAppendEntries\x12\x1a.raft.AppendEntriesRequest\x1a\x1b.raft.AppendEntriesResponse\x12$\n\x08KillNode\x12\x0b.raft.Empty\x1a\x0b.raft.Empty\x12*\n\x04Ping\x12\x11.raft.PingRequest\x1a\x0f.raft.PingReply\x12\x33\n\tGetStatus\x12\x13.raft.StatusRequest\x1a\x11.raft.StatusReplyb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'raft_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_REQUESTVOTEREQUEST']._serialized_start=29
  _globals['_REQUESTVOTEREQUEST']._serialized_end=85
  _globals['_REQUESTVOTERESPONSE']._serialized_start=87
  _globals['_REQUESTVOTERESPONSE']._serialized_end=144
  _globals['_APPENDENTRIESREQUEST']._serialized_start=146
  _globals['_APPENDENTRIESREQUEST']._serialized_end=201
  _globals['_APPENDENTRIESRESPONSE']._serialized_start=203
  _globals['_APPENDENTRIESRESPONSE']._serialized_end=257
  _globals['_STATUSREQUEST']._serialized_start=259
  _globals['_STATUSREQUEST']._serialized_end=274
  _globals['_STATUSREPLY']._serialized_start=276
  _globals['_STATUSREPLY']._serialized_end=349
  _globals['_PINGREQUEST']._serialized_start=351
  _globals['_PINGREQUEST']._serialized_end=364
  _globals['_PINGREPLY']._serialized_start=366
  _globals['_PINGREPLY']._serialized_end=394
  _globals['_RAFTSERVICE']._serialized_start=397
  _globals['_RAFTSERVICE']._serialized_end=687
# @@protoc_insertion_point(module_scope)
